# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19MWy84mgqc_5PEpTPWgx8noaj5oFpIt3
"""

import streamlit as st
import pandas as pd
from pyomo.environ import *
import plotly.graph_objects as go

# 1. 페이지 레이아웃 설정
st.set_page_config(page_title="Horticultural APP Optimizer", layout="wide")
st.title("🌿 원예장비 제조업체 총괄생산계획(APP) 최적화")

# 2. 사이드바: 파라미터 입력 [cite: 123-128]
with st.sidebar:
    st.header("📌 생산 비용 및 제약 조건 설정")
    unit_price = st.number_input("판매 단가 (천원)", value=40)
    cost_mat = st.number_input("재료비 (천원/개)", value=10)
    cost_hold = st.number_input("재고유지비 (천원/개/월)", value=2)
    cost_back = st.number_input("부재고비용 (천원/개/월)", value=5)
    w_init = st.number_input("초기 근로자 수", value=80)
    i_init = st.number_input("초기 재고량", value=1000)
    i_final = st.number_input("최종 목표 재고", value=500)

    st.markdown("---")
    st.subheader("📈 월별 수요 예측 입력")
    demand_input = st.text_input("1월~6월 수요 (쉼표 구분)", "1600, 3000, 3200, 3800, 2200, 2200")
    demand = [float(d.strip()) for d in demand_input.split(",")]

# 3. 최적화 모델 정의 함수 [cite: 182, 240, 257, 262, 271, 294]
def solve_app_optimization(D):
    m = ConcreteModel()
    T = range(1, len(D) + 1)
    TIME = range(0, len(D) + 1)

    # 결정변수 [cite: 133-140]
    m.W = Var(TIME, domain=NonNegativeReals) # 작업자
    m.H = Var(TIME, domain=NonNegativeReals) # 고용
    m.L = Var(TIME, domain=NonNegativeReals) # 해고
    m.P = Var(TIME, domain=NonNegativeReals) # 생산량
    m.I = Var(TIME, domain=NonNegativeReals) # 재고
    m.S = Var(TIME, domain=NonNegativeReals) # 부재고
    m.C = Var(TIME, domain=NonNegativeReals) # 외주
    m.O = Var(TIME, domain=NonNegativeReals) # 잔업

    # 목적함수: 비용 최소화 [cite: 143, 144]
    m.cost = Objective(expr=sum(
        (4*8*20)*m.W[t] + 6*m.O[t] + 300*m.H[t] + 500*m.L[t] +
        cost_hold*m.I[t] + cost_back*m.S[t] + cost_mat*m.P[t] + 30*m.C[t]
        for t in T), sense=minimize)

    # 제약조건 [cite: 147, 154, 157, 160, 171-176]
    m.cons = ConstraintList()
    m.cons.add(m.W[0] == w_init)
    m.cons.add(m.I[0] == i_init)
    m.cons.add(m.S[0] == 0)

    for t in T:
        m.cons.add(m.W[t] == m.W[t-1] + m.H[t] - m.L[t]) # 노동력 균형
        m.cons.add(m.P[t] <= 40*m.W[t] + m.O[t]/4)       # 생산 능력
        m.cons.add(m.I[t] == m.I[t-1] + m.P[t] + m.C[t] - D[t-1] - m.S[t-1] + m.S[t]) # 재고 균형
        m.cons.add(m.O[t] <= 10*m.W[t])                 # 초과근무 제한

    m.cons.add(m.I[len(D)] >= i_final)
    m.cons.add(m.S[len(D)] == 0)

    # Solver 실행 (GLPK)
    SolverFactory('glpk').solve(m)
    return m

# 4. 결과 출력 및 시각화
if st.button("🚀 최적 생산 계획 수립 시작"):
    model = solve_app_optimization(demand)

    # 데이터 프레임 변환
    res_data = {
        "Month": list(range(1, len(demand)+1)),
        "Demand": demand,
        "Production": [model.P[t]() for t in range(1, len(demand)+1)],
        "Inventory": [model.I[t]() for t in range(1, len(demand)+1)],
        "Workers": [model.W[t]() for t in range(1, len(demand)+1)]
    }
    df = pd.DataFrame(res_data)

    # 대시보드 구성
    col1, col2 = st.columns(2)

    with col1:
        st.subheader("📊 수요 vs 생산량")
        fig1 = go.Figure()
        fig1.add_trace(go.Scatter(x=df['Month'], y=df['Demand'], name="수요", line=dict(dash='dash')))
        fig1.add_trace(go.Bar(x=df['Month'], y=df['Production'], name="생산량"))
        st.plotly_chart(fig1, use_container_width=True)

    with col2:
        st.subheader("📦 재고 수준 변화")
        fig2 = go.Figure()
        fig2.add_trace(go.Scatter(x=df['Month'], y=df['Inventory'], fill='tozeroy', name="재고량"))
        st.plotly_chart(fig2, use_container_width=True)

    st.subheader("📋 상세 최적화 결과 테이블")
    st.table(df)
    st.success(f"최소 총 비용: {model.cost():,.0f} 천원")